### ISSUE TITLE
Videreutvikling av app

### ISSUE THREAD

**Issue by glitchdetector** [trevol1/Bacheloroppgaven-BO19G04#6]
## To-do list:
- [ ] Hente inn info fra NSB, Østfold Kollektiv
- [ ] Hente inn praktisk info, program, med mulighelt for oppdatering
- [ ] Skille mellom vanlige innlegg og sangtekst
- [ ] Testing 1 & 2
